/**:
  ros__parameters:
    wheel_radius: 0.2 # The radius of the wheel, primarily used for dead reckoning.
    wheel_width: 0.15 # The lateral width of a wheel tire, primarily used for dead reckoning.
    wheel_base: 1.5 # between front wheel center and rear wheel center
    wheel_tread: 1.0 # between left wheel center and right wheel center
    front_overhang: 0.2 # between front wheel center and vehicle front
    rear_overhang: 0.2 # between rear wheel center and vehicle rear
    left_overhang: 0.1 # between left wheel center and vehicle left
    right_overhang: 0.1 # between right wheel center and vehicle right
    vehicle_height: 2.5
    max_steer_angle: 3.0 # [rad]
