/**:
  ros__parameters:
    # ============================================
    # 室内AGV行为速度规划器参数配置
    # ============================================
    # 功能：基于场景的速度规划（停止线、障碍物等）
    # 适用场景：室内环境速度调节
    # 更新日期：2025-10-21
    # ============================================
    
    # 规划频率 [Hz]
    planning_hz: 10.0
    
    # 最大速度 [m/s]
    # 室内AGV最大运行速度
    max_velocity: 1.5
    
    # 最大加速度 [m/s²]
    max_accel: 0.5
    
    # 最大减速度 [m/s²]
    max_decel: 0.8
    
    # 最大急动度 [m/s³]
    # 室内环境需要平稳运行
    max_jerk: 0.5
    
    # 停止线行为参数
    stop_line:
      # 是否启用停止线检测
      # 室内环境可能没有标准停止线，根据需要启用
      enable: false
      
      # 停止线前停止距离 [m]
      stop_distance_before_stop_line: 0.5
      
      # 停止等待时间 [s]
      stop_wait_time: 1.0
    
    # 障碍物停止参数
    obstacle_stop:
      # 是否启用障碍物停止
      enable: true
      
      # 停止距离 [m]
      # 与障碍物保持的停止距离
      # 室内环境使用较小值
      stop_distance: 1.0
      
      # 减速距离 [m]
      # 开始减速的距离
      decel_distance: 3.0
      
      # 停止速度阈值 [m/s]
      # 低于此速度视为停止
      stop_speed_threshold: 0.01
      
      # 障碍物宽度扩展 [m]
      # 障碍物边界向外扩展的距离
      obstacle_width_expansion: 0.2
      
      # 最小障碍物高度 [m]
      # 低于此高度的障碍物将被忽略
      min_obstacle_height: 0.1
      
      # 最大障碍物高度 [m]
      # 高于此高度的障碍物将被忽略（如天花板）
      max_obstacle_height: 2.5
    
    # 速度限制参数
    speed_limit:
      # 是否启用地图速度限制
      enable: true
      
      # 速度限制缓冲 [m/s]
      # 实际速度 = 地图限速 - 缓冲
      speed_limit_buffer: 0.1
      
      # 减速提前距离 [m]
      # 进入低速区域前的减速距离
      deceleration_advance_distance: 5.0
    
    # 曲率速度限制
    curvature_speed_limit:
      # 是否启用曲率速度限制
      # 室内环境转弯较多，建议启用
      enable: true
      
      # 最大横向加速度 [m/s²]
      # 用于计算转弯速度限制
      max_lateral_accel: 0.5
      
      # 最小转弯半径 [m]
      # 室内环境转弯半径较小
      min_turn_radius: 1.0
      
      # 曲率计算窗口 [m]
      # 用于平滑曲率计算的窗口大小
      curvature_calculation_window: 3.0
    
    # 安全速度调节
    safety_speed_adjustment:
      # 是否启用安全速度调节
      enable: true
      
      # 最小安全距离 [m]
      # 与障碍物的最小安全距离
      min_safety_distance: 0.5
      
      # 速度缩放因子
      # 根据与障碍物距离动态调整速度
      # 距离越近，速度越慢
      distance_to_speed_scaling:
        # [距离[m], 速度比例]
        - [0.5, 0.0]    # 0.5米内停止
        - [1.0, 0.3]    # 1米处30%速度
        - [2.0, 0.6]    # 2米处60%速度
        - [3.0, 0.8]    # 3米处80%速度
        - [5.0, 1.0]    # 5米外全速
    
    # 通道宽度速度调节
    corridor_width_speed_adjustment:
      # 是否启用通道宽度速度调节
      # 室内环境通道宽度变化大，建议启用
      enable: true
      
      # 最小通道宽度 [m]
      # 低于此宽度将限制速度
      min_corridor_width: 1.5
      
      # 通道宽度到速度的映射
      # [通道宽度[m], 速度比例]
      width_to_speed_scaling:
        - [0.8, 0.3]    # 0.8米宽通道30%速度
        - [1.2, 0.5]    # 1.2米宽通道50%速度
        - [1.5, 0.7]    # 1.5米宽通道70%速度
        - [2.0, 1.0]    # 2米以上全速
    
    # 交叉路口行为
    intersection:
      # 是否启用交叉路口减速
      # 室内环境可能有通道交汇点
      enable: true
      
      # 交叉路口检测距离 [m]
      detection_distance: 5.0
      
      # 交叉路口减速速度 [m/s]
      intersection_speed_limit: 0.5
      
      # 交叉路口停止
      # 是否在交叉路口完全停止
      stop_at_intersection: false
      
      # 停止等待时间 [s]
      stop_wait_time: 1.0
    
    # 行人检测行为
    pedestrian_detection:
      # 是否启用行人检测响应
      # 室内环境人员较多，建议启用
      enable: true
      
      # 行人检测范围 [m]
      detection_range: 10.0
      
      # 行人停止距离 [m]
      pedestrian_stop_distance: 2.0
      
      # 行人减速距离 [m]
      pedestrian_decel_distance: 5.0
      
      # 行人存在时的速度限制 [m/s]
      pedestrian_speed_limit: 0.8
    
    # 紧急停止参数
    emergency_stop:
      # 紧急停止距离 [m]
      emergency_stop_distance: 0.3
      
      # 紧急减速度 [m/s²]
      emergency_decel: 1.5
      
      # 紧急停止触发条件
      triggers:
        # 碰撞时间阈值 [s]
        # 预计碰撞时间小于此值触发紧急停止
        time_to_collision_threshold: 1.0
        
        # 最小障碍物距离 [m]
        min_obstacle_distance: 0.3
    
    # 平滑参数
    smoothing:
      # 速度平滑窗口大小
      # 用于平滑速度变化
      velocity_smoothing_window: 5
      
      # 加速度平滑窗口大小
      acceleration_smoothing_window: 3
    
    # 调试参数
    debug:
      # 发布调试信息
      publish_debug_info: false
      
      # 打印速度规划结果
      print_velocity_planning: false
      
      # 发布速度限制可视化
      publish_velocity_limit_markers: true

